#!/usr/bin/perl
#
# File: extractb
#
# This program extracts the data from the b.* file created by
# AUTO, and puts it into a format that can be used by, say, GNUPLOT
# or MATLAB.
#

if ($#ARGV != 0)
   {
   print STDERR "One argument required.\n";
   exit;
   }
$fnroot = shift(@ARGV);
$fndat = $fnroot . ".dat";
$fnblk = $fnroot . ".blk";
$fnlbl = $fnroot . ".lbl";

open(DAT,">" . $fndat) || die "Unable to open $fndat";
open(BLK,">" . $fnblk) || die "Unable to open $fnblk";
open(LBL,">" . $fnlbl) || die "Unable to open $fnlbl";

$bcount = 0;

$flag = 0;
while (<>)
   {
   @fields = split(' ');
   if ($fields[0] != 0)
      {
      if ($flag == 0)
         {
         ++$bcount;
         $blksize = 0;
         print STDERR "Reading block $bcount\n";
         }
      print DAT join(' ',$fields[4],$fields[5],$fields[6],$fields[7],
                         $fields[8],$fields[9],$fields[10]);
      print DAT "\n";
      if (($fields[2] != 0) && ($fields[3] != 0))
         {
         print LBL join(' ',$fields[2],$fields[3],
                            $fields[4],$fields[5],$fields[6],$fields[7],
                            $fields[8],$fields[9],$fields[10]);
         print LBL "\n";
         }
      ++$blksize;
      $flag = 1;
      }
   else
      {
      if ($flag == 1)
         {
         print DAT "\n";
         print BLK "$blksize\n";
         print STDERR "Block $bcount has $blksize points.\n";
         $flag = 0;
         }
      }
   }
if ($flag == 1)
   {
   print BLK "$blksize\n";
   print STDERR "Block $bcount has $blksize points.\n";
   }

close(DAT);
close(BLK);
close(LBL);
